services:
  webapi:
    build:
      dockerfile: ./WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    ports:
      - "5000:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
  logs:
    image: mongo:latest
    ports:
      - "${LOGS_PORT}:${LOGS_PORT}"
    volumes:
      - logs-data:/data/db
volumes:
  db-data:
  logs-data:
